---
functional:
  - Требование 8 (Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре)
  - Требование 9 (Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины)
non-functional:
  - Требование 1 (Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы)
  - Требование 2 (Сайт должен быть безопасным и защищать данные пользователя)
  - Требование 3 (Пользователь должен иметь возможность искать товары по ключевому слову или категории)
  - Требование 4 (Пользователь должен иметь возможность фильтровать товары)
  - Требование 5 (Сайт должен иметь мобильную версию)
  - Требование 6 (Сайт нужно протестировать на совместимость с последними версиями браузеров)
  - Требование 7 (Важно, чтобы сайт мог обрабатывать большое количество трафика)
  - Требование 10 (Сайт должен быть доступен на различных устройствах)
implicit:
  - Цена товара должна быть положительным числом
  - Ограничить возможность пользователю добавлять большее количество товара, чем есть в наличии
  - Сайт должен быть понятным и простым в использовании
  
  
