---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Корзина будет хранится в сессии браузера
implicit:
  - Цена товара должна быть положительным числом
  - Ограничить возможность пользователю добавлять большее количество товара, чем есть в наличии
  - Сайт должен быть понятным и простым в использовании
  - Сайт должен иметь страницу регистрации и возможность входа в зарегистрированный аккаунт
  - Форма регистрации должна содержать поля (Имя, пароль, подтверждение пароля, email, номер телефона)
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  
  
